### ISSUE TITLE
Minor UI fixes

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-doc#516]
The new design is implemented and I suggest we should do a round of UI QA. Will create a checklist in this issues here after talking to the designer.

**Others**
- [x] New header design
- [x] Update overall docs site style 
  - [x] Heading styles
  - [x] Font family #465 
  - [x] Ordered list
  - [x] Unordered list
- [x] New "edit this page" button design

**Search box**
- [x] Add platform logos to indicate the platform the guide belongs to  #517 
- [x] Add no result screen #515 
- [x] Include code blocks in the search #515

**Comment by chpapa** [comment]
I think there are something everyone agrees with and needs to fix already:

1. The header is too high, it needs to be narrower.
2. Related with 1, the header should not be float above the scroll of content.

**Comment by chpapa** [comment]
#515 is one of the minor UI issues found.

**Comment by chpapa** [comment]
I think the new staging looks pretty neat, let's update it to production?
